// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';

export function ActivateUser(arg1:number):Promise<void>;

export function CreateUser(arg1:string,arg2:string,arg3:string):Promise<void>;

export function CurrentUser():Promise<models.UserResponse>;

export function DeactivateUser(arg1:number):Promise<void>;

export function IsAuthenticated():Promise<boolean>;

export function ListUsers():Promise<Array<models.UserResponse>>;

export function Login(arg1:string,arg2:string):Promise<models.UserResponse>;

export function Logout():Promise<void>;
