// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ActivateUser(arg1) {
  return window['go']['handlers']['AuthHandler']['ActivateUser'](arg1);
}

export function CreateUser(arg1, arg2, arg3) {
  return window['go']['handlers']['AuthHandler']['CreateUser'](arg1, arg2, arg3);
}

export function CurrentUser() {
  return window['go']['handlers']['AuthHandler']['CurrentUser']();
}

export function DeactivateUser(arg1) {
  return window['go']['handlers']['AuthHandler']['DeactivateUser'](arg1);
}

export function IsAuthenticated() {
  return window['go']['handlers']['AuthHandler']['IsAuthenticated']();
}

export function ListUsers() {
  return window['go']['handlers']['AuthHandler']['ListUsers']();
}

export function Login(arg1, arg2) {
  return window['go']['handlers']['AuthHandler']['Login'](arg1, arg2);
}

export function Logout() {
  return window['go']['handlers']['AuthHandler']['Logout']();
}
