// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';

export function GetComboChartData(arg1:number,arg2:number):Promise<Record<number, Array<models.ChartPoint>>>;
