// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';

export function AddComment(arg1:number,arg2:any,arg3:string,arg4:number):Promise<void>;

export function GetCommentsForChart(arg1:number):Promise<Array<models.CommentResponse>>;

export function GetCommentsForCombo(arg1:number):Promise<Array<models.CommentResponse>>;
