// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddComment(arg1, arg2, arg3, arg4) {
  return window['go']['handlers']['CommentsHandler']['AddComment'](arg1, arg2, arg3, arg4);
}

export function GetCommentsForChart(arg1) {
  return window['go']['handlers']['CommentsHandler']['GetCommentsForChart'](arg1);
}

export function GetCommentsForCombo(arg1, arg2) {
  return window['go']['handlers']['CommentsHandler']['GetCommentsForCombo'](arg1, arg2);
}
