// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetDBPath() {
  return window['go']['handlers']['ConfigHandler']['GetDBPath']();
}

export function InitDB() {
  return window['go']['handlers']['ConfigHandler']['InitDB']();
}

export function OpenDBFilePicker() {
  return window['go']['handlers']['ConfigHandler']['OpenDBFilePicker']();
}

export function SetContext(arg1) {
  return window['go']['handlers']['ConfigHandler']['SetContext'](arg1);
}

export function SetDBPath(arg1) {
  return window['go']['handlers']['ConfigHandler']['SetDBPath'](arg1);
}
