// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetAnalytesForCombo(arg1, arg2) {
  return window['go']['handlers']['DataEntryHandler']['GetAnalytesForCombo'](arg1, arg2);
}

export function GetChartResults(arg1) {
  return window['go']['handlers']['DataEntryHandler']['GetChartResults'](arg1);
}

export function ListMethodsWithMaterials() {
  return window['go']['handlers']['DataEntryHandler']['ListMethodsWithMaterials']();
}

export function SaveChart(arg1, arg2, arg3, arg4) {
  return window['go']['handlers']['DataEntryHandler']['SaveChart'](arg1, arg2, arg3, arg4);
}
