// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateAnalyte(arg1, arg2) {
  return window['go']['handlers']['LibraryHandler']['CreateAnalyte'](arg1, arg2);
}

export function CreateMaterial(arg1, arg2) {
  return window['go']['handlers']['LibraryHandler']['CreateMaterial'](arg1, arg2);
}

export function CreateMethod(arg1, arg2) {
  return window['go']['handlers']['LibraryHandler']['CreateMethod'](arg1, arg2);
}

export function ListAnalytes() {
  return window['go']['handlers']['LibraryHandler']['ListAnalytes']();
}

export function ListMaterials() {
  return window['go']['handlers']['LibraryHandler']['ListMaterials']();
}

export function ListMethods() {
  return window['go']['handlers']['LibraryHandler']['ListMethods']();
}
