// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';

export function CreateAnalyte(arg1:string,arg2:string):Promise<void>;

export function CreateMaterial(arg1:string,arg2:string):Promise<void>;

export function CreateMethod(arg1:string,arg2:string):Promise<void>;

export function ListAnalytes():Promise<Array<models.Analyte>>;

export function ListMaterials():Promise<Array<models.Material>>;

export function ListMethods():Promise<Array<models.Method>>;
