// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DeleteControlLimitRegionSet(arg1, arg2, arg3) {
  return window['go']['handlers']['LimitsHandler']['DeleteControlLimitRegionSet'](arg1, arg2, arg3);
}

export function GetCurrentSequencesForMMAs(arg1) {
  return window['go']['handlers']['LimitsHandler']['GetCurrentSequencesForMMAs'](arg1);
}

export function ListControlLimitRegionsForCombo(arg1) {
  return window['go']['handlers']['LimitsHandler']['ListControlLimitRegionsForCombo'](arg1);
}

export function SaveControlLimitRegions(arg1) {
  return window['go']['handlers']['LimitsHandler']['SaveControlLimitRegions'](arg1);
}
