// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';

export function DeleteControlLimitRegionSet(arg1:number,arg2:number,arg3:number):Promise<void>;

export function GetCurrentSequencesForMMAs(arg1:Array<number>):Promise<Record<number, number>>;

export function ListControlLimitRegionsForCombo(arg1:number):Promise<Array<models.ControlLimitRegion>>;

export function SaveControlLimitRegions(arg1:Array<models.ControlLimitRegion>):Promise<void>;
