// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ActivateMMA(arg1) {
  return window['go']['handlers']['MMAHandler']['ActivateMMA'](arg1);
}

export function AddAnalyteToMMA(arg1, arg2, arg3, arg4) {
  return window['go']['handlers']['MMAHandler']['AddAnalyteToMMA'](arg1, arg2, arg3, arg4);
}

export function DeactivateMMA(arg1) {
  return window['go']['handlers']['MMAHandler']['DeactivateMMA'](arg1);
}

export function ListAllMMAs() {
  return window['go']['handlers']['MMAHandler']['ListAllMMAs']();
}

export function ListMMAsForMethod(arg1) {
  return window['go']['handlers']['MMAHandler']['ListMMAsForMethod'](arg1);
}

export function ListUsedMMAIDs() {
  return window['go']['handlers']['MMAHandler']['ListUsedMMAIDs']();
}

export function RemoveAnalyteFromMMA(arg1) {
  return window['go']['handlers']['MMAHandler']['RemoveAnalyteFromMMA'](arg1);
}

export function UpdateDisplayOrders(arg1, arg2) {
  return window['go']['handlers']['MMAHandler']['UpdateDisplayOrders'](arg1, arg2);
}
