// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';

export function ActivateCombo(arg1:number):Promise<void>;

export function AddAnalyteToMMA(arg1:number,arg2:number,arg3:number):Promise<void>;

export function DeactivateCombo(arg1:number):Promise<void>;

export function EnsureMethodMaterial(arg1:number,arg2:number):Promise<number>;

export function ListAllMMAs():Promise<Array<models.MMAEntry>>;

export function ListMMAsForMethod(arg1:number):Promise<Array<models.MMAEntry>>;

export function ListUsedMMAIDs():Promise<Array<number>>;

export function RemoveAnalyteFromMMA(arg1:number):Promise<void>;

export function SetRenderChart(arg1:number,arg2:boolean):Promise<void>;

export function UpdateDisplayOrders(arg1:Array<number>,arg2:Array<number>):Promise<void>;
