// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ActivateCombo(arg1) {
  return window['go']['handlers']['MMAHandler']['ActivateCombo'](arg1);
}

export function AddAnalyteToMMA(arg1, arg2, arg3) {
  return window['go']['handlers']['MMAHandler']['AddAnalyteToMMA'](arg1, arg2, arg3);
}

export function DeactivateCombo(arg1) {
  return window['go']['handlers']['MMAHandler']['DeactivateCombo'](arg1);
}

export function EnsureMethodMaterial(arg1, arg2) {
  return window['go']['handlers']['MMAHandler']['EnsureMethodMaterial'](arg1, arg2);
}

export function ListAllMMAs() {
  return window['go']['handlers']['MMAHandler']['ListAllMMAs']();
}

export function ListMMAsForMethod(arg1) {
  return window['go']['handlers']['MMAHandler']['ListMMAsForMethod'](arg1);
}

export function ListUsedMMAIDs() {
  return window['go']['handlers']['MMAHandler']['ListUsedMMAIDs']();
}

export function RemoveAnalyteFromMMA(arg1) {
  return window['go']['handlers']['MMAHandler']['RemoveAnalyteFromMMA'](arg1);
}

export function SetRenderChart(arg1, arg2) {
  return window['go']['handlers']['MMAHandler']['SetRenderChart'](arg1, arg2);
}

export function UpdateDisplayOrders(arg1, arg2) {
  return window['go']['handlers']['MMAHandler']['UpdateDisplayOrders'](arg1, arg2);
}
