// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateAdminUser(arg1, arg2) {
  return window['go']['handlers']['SetupHandler']['CreateAdminUser'](arg1, arg2);
}

export function NeedsSetup() {
  return window['go']['handlers']['SetupHandler']['NeedsSetup']();
}

export function UserExists(arg1) {
  return window['go']['handlers']['SetupHandler']['UserExists'](arg1);
}
