// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateAdminUser(arg1:string,arg2:string):Promise<void>;

export function NeedsSetup():Promise<boolean>;

export function UserExists(arg1:string):Promise<boolean>;
