// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateMMARuleSet(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11) {
  return window['go']['handlers']['SPCRuleSetHandler']['CreateMMARuleSet'](arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11);
}

export function GetEffectiveRuleSetForCombo(arg1, arg2) {
  return window['go']['handlers']['SPCRuleSetHandler']['GetEffectiveRuleSetForCombo'](arg1, arg2);
}

export function GetGlobalRuleSet() {
  return window['go']['handlers']['SPCRuleSetHandler']['GetGlobalRuleSet']();
}

export function GetRuleSetsForMMA(arg1) {
  return window['go']['handlers']['SPCRuleSetHandler']['GetRuleSetsForMMA'](arg1);
}

export function UpdateGlobalRuleSet(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9) {
  return window['go']['handlers']['SPCRuleSetHandler']['UpdateGlobalRuleSet'](arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9);
}
